services:
  zookeeper:
    image: quay.io/debezium/zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    env_file:
      - .env
    networks:
      - studdy-buddy-net 
    container_name: zookeeper
  kafka:
    image: quay.io/debezium/kafka
    ports:
      - 9092:9092
    env_file:
      - .env
    networks:
      - studdy-buddy-net 
    container_name: kafka
    depends_on:
      - zookeeper
  connect:
    image: connector
    build: ../replicator
    ports:
      - 8083:8083
    networks:
      - studdy-buddy-net 
    container_name: connect
    env_file:
      - .env
    volumes:
      - ./.env:/data/credentials.properties
    depends_on:
      - kafka

networks:
  studdy-buddy-net:
    name: studdy-buddy-net 
    driver: bridge