services:
  user-mysql:
    image: mysql:latest
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${USER_MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${USER_MYSQL_ROOT_PASSWORD}
    networks:
      - studdy-buddy-net
    container_name: user-mysql

  user:
    build: ../user
    image: user
    env_file:
      - .env
    environment:
      - ConnectionStrings__DbConnectionString=${USER_MYSQL_CONNECTION_STRING}
      - ASPNETCORE_URLS=${USER_PORT}
      - Kafka_BootstrapServers=${USER_KAFKA_BOOTSTRAP_SERVERS}
    ports:
      - 5500:80
    networks:
      - studdy-buddy-net
    container_name: user
    restart: on-failure
    depends_on:
      - user-mysql
  user_db_cfg:
    build:
      context: .
      dockerfile: ../replicator/alpine.Dockerfile
    container_name: user_db_cfg
    env_file:
      - .env
    depends_on:
      - user
      - kafka
      - connect
    restart: on-failure
    ports:
      - 8080:80
    networks:
      - studdy-buddy-net
    volumes:
      - ./replicas/source.user.sh:/tmp/entrypoint.sh
    command: sh -c "sh /tmp/entrypoint.sh"
